version: '3.8'
services:
  backend:
    build: ./backend
    ports:
      - '3000:3000'
    env_file:
      - ./backend/.env
    volumes:
      - uploads:/app/uploads
      - orders-data:/app/data
  frontend:
    build: ./frontend
    ports:
      - '8080:80'
    depends_on:
      - backend

volumes:
  uploads:
  orders-data:
